name: MafiaUHC
version: 0.0.8.15
author: NoursInDev
main: org.noursindev.mafiauhc.MafiaUHC
commands:
  mf:
    description: Main command for MafiaUHC
    usage: /mf <subcommand>
    aliases:
      - mafiauhc
  mfc :
    description: Config command for MafiaUHC
    usage: /mfc <subcommand>
    aliases:
      - mfconfig
      - mafiauhcconfig